### ISSUE TITLE
Format of messages

### ISSUE THREAD

**Issue by van-de-bugger** [plicease/Test-Fixme#2]
Hi,

Currently test prints messages like this:

    # File: './lib/lib/Dist/Zilla/Plugin/Manifest/Write.pm'
    #     67      with 'Dist::Zilla::Role::FileGatherer'; # FIXME

It would be nice if format of messages follow the scheme used in Perl:

    message at <file> line <linenumber>

For example:

    # FIXME found at file ./lib/lib/Dist/Zilla/Plugin/Manifest/Write.pm line 67:
    #       with 'Dist::Zilla::Role::FileGatherer'; # FIXME

BTW, `prove` also uses such format:

    #   Failed test ''./lib/lib/Dist/Zilla/Plugin/Manifest/Write.pm''
    #   at xt/release/fixme.t line 8.

**Comment by plicease** [comment]
That does seem like a better formatting, and I don't think using a more standard formatting should break things.  I will give it some thought and maybe we can do this.

**Comment by van-de-bugger** [comment]
Thanks. Uniform messages help in various IDEs — you can click on the line and IDE will open the problem file and place the caret in problem line. That's very convenient.

BTW, `perlcritic` can print messages in 11 different formats (see `--verbose` in [OPTIONS](https://metacpan.org/pod/distribution/Perl-Critic/bin/perlcritic#OPTIONS)). I do *not* request all eleven formats, to me Perl format is enough. It is just an example of purpose and implementation.

**Comment by plicease** [comment]
I've added the `format` option and uploaded a dev release as `0.14_01`.  The original output format predates me as maintainer of this module, but I find it a little more readable when there are many offending patterns in the file, so I am going to keep that as the default.  You can override this setting with the `TEST_FIXME_FORMAT` environment variable, this will override the value in the test file if it is present, so even if you are sharing code bases with someone who explicitly sets it one way you can set it the other way for your own usage.  I expect to do a production release some time next week.

**Comment by van-de-bugger** [comment]
Hi, I am looking into [documentation](https://metacpan.org/pod/release/PLICEASE/Test-Fixme-0.14_01-TRIAL/lib/Test/Fixme.pm), it seems you forget to make some paragraphs verbatim. Description of format is not very readable.

**Comment by plicease** [comment]
Indeed I think I was lacking in caffeine when I was working on the documentation.

The override for format makes sense if you consider from a project level I care primarily that the test passes or does not.  From a user level, individuals working on the same projects are more likely to be using different environments so it makes sense for them to be able to override the format if they are using an IDE.

**Comment by van-de-bugger** [comment]
Hi, it seems you still suffer from lack of caffeine. Now the test prints:

    # Pattern found at ./blib/lib/Dist/Zilla/Role/Hooker.pm at 78:
    #      default     => sub { [] },  # FIXME

i. e.:

    message at <file> at <line>
    #                 ^^

"at" is printed twice, that's wrong. Please replace the second "at" with "line":

    message AT <file> LINE <line>
    #       ^^        ^^^^

About env var: reasonable developer would not hardcode format without a serious reason. But when the reason is serious, developer wants to make sure desired format is set. Consider a case: you are writing a test on your `Test::Fixme`, and want to check that your code works:

    run_tests( ..., format => 'perl' ); ...check output...
    run_tests( ..., format => 'original' ); ...check output...

Everything work on your system. But now I want to install `Text::Fixme`:

    $ cpanm Text::Fixme

`cpanm` run the tests before installing. And bang! One test failed, installation aborted. Because I have added `TEST_FIXME_FORMAT=perl` to my environment long time ago. To make sure the test works regardless of the user preferences, you will have to write in the test:

    $ENV{TEST_FIXME_FORMAT} = 'per'; run_tests( ... ); ...check output...
    $ENV{TEST_FIXME_FORMAT} = 'original'; run_tests( ... ); ...check output...

Looks ugly.

Thus: By give the environment variable priority, you cannot guarantee "user right" to specify desired format, because developer can set environment variable in the code. But such a decision complicates code when developer really wants to specify the format.

So, please change your mind and let environment variable to be the second format source, if format is not set explicitly in the code.

**Comment by plicease** [comment]
I guess I disagree with you about the environment variable.  The test suite passes either way.  I don't recommend writing tests that depend on the output of `Test::Fixme`.

**Comment by van-de-bugger** [comment]
>  I don't recommend writing tests that depend on the output of Test::Fixme.

But how do you test `Test::Fixme`?
